In [1]:
import bqplot
import numpy as np
import ipywidgets

1. Random Line plot

In [4]:
x = np.arange(200)

In [3]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
y = np.random.random(200)

In [6]:
y

array([0.42362663, 0.59317859, 0.05578036, 0.45457831, 0.20602512,
       0.95945817, 0.00999188, 0.58377647, 0.05891527, 0.82901851,
       0.00643721, 0.69655844, 0.34089191, 0.64505655, 0.36590367,
       0.48645231, 0.72578387, 0.18502154, 0.52683136, 0.34743843,
       0.75917155, 0.0807035 , 0.58024412, 0.60140135, 0.38333886,
       0.85414883, 0.42623785, 0.37369243, 0.62423434, 0.64511937,
       0.04627737, 0.27486771, 0.52637756, 0.9298766 , 0.60270445,
       0.00968312, 0.41212104, 0.30481824, 0.31770872, 0.21950504,
       0.03997044, 0.43429789, 0.76666375, 0.48804995, 0.86694999,
       0.92757495, 0.84414682, 0.95124472, 0.13524649, 0.38565799,
       0.36312668, 0.82191053, 0.37620819, 0.05042173, 0.66581343,
       0.47797512, 0.16613116, 0.67094632, 0.48729265, 0.96900738,
       0.620637  , 0.42277321, 0.56699583, 0.50759092, 0.56716994,
       0.36806069, 0.64244105, 0.64971666, 0.39398253, 0.70970613,
       0.55780122, 0.15230992, 0.16637114, 0.19958412, 0.90330

In [7]:
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [8]:
lines = bqplot.Lines(x=x, y=y, scales = {'x':x_sc, 'y':y_sc})

In [9]:
ax_x = bqplot.Axis(scale=x_sc, label='X Value')
ax_y = bqplot.Axis(scale=y_sc, label='Y Value', orientation='vertical')

In [10]:
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y])

In [11]:
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

In [12]:
bqplot.Lines?

In [13]:
pz = bqplot.interacts.PanZoom( scales = {'x': [x_sc], 'y': [y_sc]})

In [14]:
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y], interaction=pz)

In [15]:
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

2. Random scatter plot

In [16]:
x = np.random.random(150)

In [17]:
x

array([0.30566796, 0.39284088, 0.30035237, 0.55086614, 0.15508039,
       0.16708462, 0.31409576, 0.61725956, 0.18624949, 0.52747483,
       0.27859136, 0.87734436, 0.24444242, 0.94260673, 0.19930788,
       0.51491333, 0.58454452, 0.34283635, 0.31018149, 0.91225838,
       0.54245663, 0.48477164, 0.31529625, 0.52528665, 0.01586104,
       0.065169  , 0.82931803, 0.34381456, 0.34129433, 0.87589632,
       0.98873431, 0.2414659 , 0.59047227, 0.86930287, 0.18034181,
       0.87548202, 0.06156778, 0.28494784, 0.11857939, 0.62994016,
       0.09370598, 0.75658743, 0.84886734, 0.57335369, 0.72760431,
       0.21716128, 0.12386798, 0.16336555, 0.78983039, 0.21679395,
       0.44296881, 0.31778578, 0.92959553, 0.40702315, 0.22219033,
       0.79559048, 0.30599765, 0.23117427, 0.64168415, 0.86652279,
       0.80084854, 0.43404553, 0.56860244, 0.38369369, 0.71128898,
       0.50246399, 0.20667882, 0.19345985, 0.28376116, 0.70953967,
       0.59453754, 0.66546229, 0.42214805, 0.32027922, 0.02729

In [30]:
y = np.random.random(200)

In [31]:
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [32]:
ax_x = bqplot.Axis(scale = x_sc, label="X")
ax_y = bqplot.Axis(scale = y_sc, label="Y", orientation='vertical')

In [33]:
scatters = bqplot.Scatter(x = x, y = y, scales={'x':x_sc, 'y':y_sc})

In [34]:
selector = bqplot.interacts.FastIntervalSelector(scale=x_sc, marks=[scatters])

In [35]:
fig = bqplot.Figure(marks=[scatters], axes=[ax_x, ax_y], interaction = selector)
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

In [40]:
scatters.unselected_style = {'opacity':1} # a little see-through when not selected
scatters.selected_style={'fill':'blue', 'stroke':'pink'}

In [41]:
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

3. Heatmap (2d Data) with random points

In [42]:
data = np.random.random((10,10) )

In [43]:
data

array([[0.30380062, 0.71988318, 0.83366745, 0.97062193, 0.66550022,
        0.27209248, 0.07339014, 0.91889766, 0.97114139, 0.85596736],
       [0.28830723, 0.3974712 , 0.29709165, 0.35325363, 0.65031349,
        0.14798221, 0.66072775, 0.46089853, 0.67935222, 0.33713895],
       [0.87156484, 0.29798534, 0.97736532, 0.96641327, 0.84144172,
        0.12092815, 0.46475994, 0.47705785, 0.46462724, 0.75723152],
       [0.13776091, 0.60895217, 0.18611581, 0.11168515, 0.07781973,
        0.33900714, 0.79338197, 0.8224566 , 0.39291352, 0.73380652],
       [0.49565555, 0.86292599, 0.68419398, 0.41666576, 0.03888006,
        0.84323293, 0.45677628, 0.219961  , 0.16727487, 0.19782829],
       [0.97350625, 0.73922886, 0.9324205 , 0.8587859 , 0.26372982,
        0.52064183, 0.70389285, 0.47670145, 0.51699033, 0.08026905],
       [0.87623288, 0.61758173, 0.77572402, 0.77001862, 0.58367708,
        0.95608903, 0.22023171, 0.37984021, 0.94357054, 0.05140584],
       [0.5816757 , 0.78737586, 0.8239403

In [45]:
data[0,1]

0.7198831777869346

In [49]:
col_sc = bqplot.ColorScale()

In [50]:
heat_map = bqplot.GridHeatMap(color = data, scales = {'color':col_sc})

In [51]:
fig = bqplot.Figure(marks = [heat_map])

In [52]:
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.30380…

In [67]:
col_sc = bqplot.ColorScale(scheme="Greens") 

In [68]:
heat_map = bqplot.GridHeatMap(color = data, scales = {'color':col_sc})

In [69]:
fig = bqplot.Figure(marks = [heat_map] )

In [70]:
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.30380…

In [71]:
data3d = np.random.random( (10,10, 10))

In [72]:
data3d.shape

(10, 10, 10)